language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - ~/.cache
before_install:
  - npm install -g json-server
install:
  - yarn install --frozen-lockfile
script:
  - yarn run dev
  - $(yarn bin)/cypress run