language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - ~/.cache
install:
  - yarn ci
script:
  - $(yarn bin)/run dev
  - $(yarn bin)/cypress run --record